version: "3"
 
services:
  pythonmelero:
    image: "pythonmelero"
    #Puerto de exposici√≥n y escucha
    ports:
      - "5001:5000"
    networks:
      - mynet
    
networks:
  mynet:
    driver: bridge


#Volumenes
#Para guardar el proyecto en directorio donde se ejecutar. docker-compose tiene que ejecutarse en esa lugar. ruta relativa
#Para que pueda hacer uso este contenedor de aplicaciones de docker
